config/routes.rb
Rails.application.routes.draw do
  get '/welcome/:first_name', to: 'welcome#show'
  get '/team', to: 'static#index'
  get '/contact', to: 'static#contact'
  get '/accueil', to: 'gossips#index'
  # get 'gossips/display'
  get '/city', to:'gossips#location'
  # get '/gossips/:id', to: 'gossip#individual'
  # get '/gossips/:id/edit', to: 'gossip#edit'
  resources :gossips do
    resources :likes 
  end 
  get '/author/:id', to: 'gossip#author'
  # get '/sessions', to: 'sessions#profile'
  delete '/sessions', to: 'sessions#destroy'
  # get '/sessions/signin', to: 'sessions#new'
  resources :sessions, only: [:new, :create]
  resources :users
  # get '/login', to:'users#create'
  get '/welcome', to: 'welcome#show'
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
    has_many :gossips
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    belongs_to :city
    has_many :tags
    has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
end

app/models/message_receiver.rb
class MessageReceiver < ApplicationRecord
    belongs_to :private_message
    belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :message_receivers
    has_many :recipients, class_name: "User", through: :message_receivers, source: :user
end

app/models/session.rb
class Session
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city, required: false
    has_many :gossips

    has_many :sent_private_messages, class_name: "PrivateMessage", foreign_key: 'sender_id'

    has_many :message_receivers
    has_many :received_private_messages, class_name: "PrivateMessage", through: :message_receivers

    has_many :likes, dependent: :destroy

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper


  def require_user
    redirect_to new_session_path unless current_user
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :require_user, only: [:destroy, :edit, :create, :new]
  def index
    @gossips = Gossip.all
  end
  def location 
    @gossips = Gossip.all
    @cities = City.all
  end 
  def show 
    @gossip= Gossip.find(params[:id])
  end
  def author 
    @user= User.find(params[:id])
  end
  def new
    @gossip = Gossip.new 
  end 
  def create
    city = City.find_by_name(params[:gossip][:city])
    @gossip = current_user.gossips.new(title: params[:gossip][:title], content: params[:gossip][:content], city: city)
    @gossip.save!
    flash[:info] = "Potin bien créé !"
    redirect_to '/accueil'

    # @gossip = Gossip.create(gossip_params)
    # @gossip.user = @current_user
    # if @gossip.save
    #   flash[:success] = "Potin bien créé !"
    #   redirect_to root_path
    # else
    #   render :new
    # end

  end
  def update
    # params.delete(:id)
    @gossip = Gossip.find(params[:id])

    if @gossip.update(params.require(:gossip).permit(:title, :content))
      redirect_to @gossip
    else
      render :edit
    end
  end
  def edit
    @gossip = Gossip.find(params[:id])
    # @article.update(post_params)
    # redirect_to articles_path
  end
  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path 
  end 
  private
  def post_params
    post_params = params.require(:gossips).permit(:title, :content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_gossip
    before_action :require_user

    def index
        @likes = Like.all
    end

    def create 
        @gossip.likes.create(user_id: current_user.id)
        redirect_to city_path 
    end 

    private 

    def find_gossip
        @gossip = Gossip.find(params[:gossip_id])
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include SessionsHelper
    # before_action :authenticate_user, only: [:index]
    
    # on code quelque chose qui permet d'afficher le dashboard de l'utilisateur
    # def index
        
    # end

        #new correspond à la page de login
        def new
            @user=User.new
            # @user = User.create(params.require(:user).permit(:username,        
            # :password))
            # session[:user_id] = @user.id
            # redirect_to '/welcome'
        end
    
        #create effectue l'authentification (traitement des informations saisies dans la page login et sauvegarde de l'info de l'utilisateur connecté dans session)
        def create
            # cherche s'il existe un utilisateur en base avec l’e-mail
            user = User.find_by(email: params[:user][:email])
            # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
            if user && user.authenticate(params[:user][:password])
                session[:user_id] = user.id
                # redirige où tu veux, avec un flash ou pas
                flash.now[:success] = 'Welcome!'
                redirect_to gossips_path
            else
                @user=User.new
                flash.now[:info] = 'Invalid email/password combination'
                render 'new'
            end
        end
    
        #destroy correspond au logout
        def destroy
            # session.delete(:user_id)
            session[:user_id] = nil
            #redirect_to accueil_path
            flash.now[:info] = 'goodbye :('
            redirect_to gossips_path
        end 
    
    private
    
    # def authenticate_user
    #     unless current_user
    #         flash[:info] = "Please log in."
    #         redirect_to new_session_path
    #     end
    # end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def index 
    end
    def contact
    end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    def create
        # binding.pry
        @user = User.new(email: params[:user][:email], password: params[:user][:password])
        @user.save!
        # @user = User.create!(params.require(:user).permit(:username, :password))
        session[:user_id] = @user.id
        redirect_to '/welcome'
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts  params[:first_name]
    puts "$" * 60
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end
    def log_in(user)
        session[:user_id] = user.id
    end
    #rajouter if current_user ou oder une méthode logged_in? dans le helper. Cette méthode te retournerait true si session[:user_id] est non-nil et false dans le cas contraire.
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/author.html.erb
<!doctype html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<header>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/accueil">Accueil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
       <li class="nav-item active">
        <a class="nav-link" href="/city">Ville <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/team">Team <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
    </ul>
  </div>
</nav>

</header>

<body style="margin:30px">
    <h1> Auteur : <%= @user.first_name %> </h1>
      <p> prénom : <%= @user.first_name %> </p>
      <p> nom : <%= @user.last_name %> </p>
      <p> email : <%= @user.email %> </p>
      <p> age : <%= @user.age %> </p>
      <p> ville : <%= @user.city.name %> </p>

      <a href="/accueil"> ⬅️ Go back</a>
</body>

</html>

app/views/gossips/edit.html.erb
<!doctype html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<header>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/accueil">Accueil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
       <li class="nav-item active">
        <a class="nav-link" href="/city">Ville <span class="sr-only">(current)</span></a>
      </li>
        <a class="nav-link" href="/team">Team <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
    </ul>
  </div>
</nav>

</header>

<body style="margin:30px">

<h1> Modifier le Gossip </h1>

<%=form_for @gossip do |f|%>

<div class="form-group">
    <label> Titre du Gossip : </label>
    <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
    <label> Contenu </label>
    <%= f.text_area :content, class: 'form-control' %>
</div>

<div class="form-group">
    <button type="submit"> Modifier l'article </button>
</div>

<%end%>

<a href="<%= gossip_path(@gossip) %>"> ⬅️ Cancel</a>

</body>
</html>

app/views/gossips/index.html.erb
<!doctype html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<header>

<b><%= flash[:info] %></b>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/accueil">Accueil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/city">Ville <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/team">Team <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
      <li class="nav-item">
        <% if current_user %>
          <%= link_to "Log out", sessions_path, method: :delete %>
        <% else %>
          <%= link_to "Sign in ", new_session_path %>
          <%= link_to "Sign up ", new_user_path %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

</header>

<body style="margin:30px">

<h1> 👋 Helloooo !! 🎉 </h1>
<h2> ✉️🔥 Voici les derniers potins ☕️ : </h2>

<div class="row">


<%= link_to "Create new gossip", new_gossip_path %>

<% @gossips.each do |gossip| %>
 
  <div class="col-sm-6">
    <div class="card" >
      <div class="card-body">
        <a href="/gossips/<%= gossip.id %>" class="card-title">
          <%= gossip.city.name %> :
          <%= gossip.title %>
        </a>
      </div>
    </div>
  </div>

<% end %>

</div>

</body>

</html>

app/views/gossips/location.html.erb
<!doctype html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<header>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/accueil">Accueil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/city">Ville <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/team">Team</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
    </li>
    </ul>
  </div>
</nav>

</header>

<body style="margin:30px">

<h1> Hey !! 🎉 </h1>
<h2> Voici les potins par ville 📍🏙 : </h2>

<div class="column">

<% @cities.each do |city| %>
  <h3><%= city.name %></h3>
  <% city.gossips.each do |gossip| %>
      <div class="col-sm-6">
          <div class="card" >
              <%= button_to 'Like', gossip_likes_path(gossip), method: :post %>
              <p><%= gossip.likes.count %> <%= (gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
              <div class="card-body">
                  <a href="/gossips/<%= gossip.id %>" class="card-title">
                      <%= gossip.title %>"
                  </a>
              </div>  
          </div>
      </div>
  <% end %>
<% end %>



</div>

</body>

</html>

app/views/gossips/new.html.erb
<!doctype html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<header>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/accueil">Accueil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
       <li class="nav-item active">
        <a class="nav-link" href="/city">Ville <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/team">Team <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
    </ul>
  </div>
</nav>

</header>

<body style="margin:30px">

<h1>Create Gossip</h1>
<b><%= flash[:info] %></b>


<%= form_for @gossip do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :content %><br>
  <%= f.text_field :content %><br>
  <%= f.label :city %><br>
  <%= f.text_field :city %><br>
  <%= f.submit "noice" %>
<%end%>
</body>
</html>

app/views/gossips/show.html.erb
<!doctype html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<header>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/accueil">Accueil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
       <li class="nav-item active">
        <a class="nav-link" href="/city">Ville <span class="sr-only">(current)</span></a>
      </li>
        <a class="nav-link" href="/team">Team <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
    </ul>
  </div>
</nav>

</header>

<body style="margin:30px">

    <h1> Voici la page du potin n° <%= @gossip.id %> </h1>
      <p>
          <a href="/author/<%= @gossip.user.id %>"> Son auteur : <%= @gossip.user.first_name %> </a>
      </p>
      <p>
      <a> Titre : "<%= @gossip.title %>" </a>
      </p>
      <p>
          <a> Le contenu du potin : "<%= @gossip.content %>" </a>
      </p>
      <p> 
      <a> Potin crée le <%= @gossip.created_at %> </a>
      </p>
      <p>
      <a> Ville : <%= @gossip.city.name %> </a>
      </p>
      <%= link_to "edit", edit_gossip_path(@gossip) %><br>
      <%= link_to "delete", gossip_path(@gossip), method: :delete %><br>

      <a href="<%= gossips_path %>"> ⬅️ Go back</a>

</body>

</html>

app/views/users/create.html.erb
<h1>Login</h1>
   <%= form_tag '/login' do %>
   <%= label_tag :username%>
   <%= text_field_tag :username %>
   <%= label_tag :password%>
   <%= password_field_tag :password%>
   <%= submit_tag "Login"%>
<%end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :email%><br>
  <%= f.text_field :email%><br>
  <%= f.label :password %>(6 charachters or more)<br>
  <%= f.password_field :password%><br>
  <%= f.submit %>
<%end%>

app/views/welcome/show.html.erb
<!doctype html>
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<header>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/accueil">Accueil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/team">Team <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
    </ul>
  </div>
</nav>

</header>

<body style="margin:30px">

<h1> Welcome <%= params[:first_name] %> </h1>
<p> Que penses-tu de mon super site de potins ? Sympa, non ? </p>

</body>

</html>